### ISSUE TITLE
Escrever a Premissa do Jogo

### ISSUE THREAD

**Issue by beatriz-paz** [gameif/jogo-web#1]

**Comment by beatriz-paz** [comment]
Além de escrever a premissa do jogo, devemos gerar um arquivo em HTML da mesma.

**Comment by YasminV12** [comment]
Quem diria que para uma nação conseguir os direitos básicos fosse necessário instigar uma guerra!

Infelizmente isso acontece. Inicia-se então a terceira guerra mundial, nações contra nações disputando o controle do poder econômico. E você está convocado a lutar pelos direitos do seu país. Mas, e se para isso, sua família para exposto ao perigo? Escolhas deverão ser tomadas, perigos serão enfrentados e o desfecho dessa trama dependerá de você.
