### ISSUE TITLE
[Exercício] Converter primeiro nome em códigos de linhas

### ISSUE THREAD

**Issue by beatriz-paz** [gameif/jogo-web#6]
Como exercício da disciplina, pegar o primeiro nome e:

1.Converter em números decimais tendo como referência a tabela ASCII.
2.Converter cada número decimal em uma cadeia de 8 bits em binário.
3.Desenhar, seja no papel ou outra ferramenta (planilha, por exemplo), em 3 códigos de linha:
  i.NRZ
 ii.MLT-3
iii.PAM5

**Comment by YasminV12** [comment]
[Ativ 1 CAB.pdf](https://github.com/gameif/jogo-web/files/5699328/Ativ.1.CAB.pdf)
Tarefa Código de Linha Concluída

**Comment by beatriz-paz** [comment]
Exercício resolvido:

[01 - Exercício - Convertendo Nome em Código de Linha.xlsx](https://github.com/gameif/jogo-web/files/5699382/01.-.Exercicio.-.Convertendo.Nome.em.Codigo.de.Linha.xlsx)

**Comment by YasminV12** [comment]
[Ativ 1 CAB.pdf](https://github.com/gameif/jogo-web/files/5703792/Ativ.1.CAB.pdf)
Tarefa Corrigida!

**Comment by ghost** [comment]
> Exercício resolvido:
> 
> [01 - Exercício - Convertendo Nome em Código de Linha.xlsx](https://github.com/gameif/jogo-web/files/5699382/01.-.Exercicio.-.Convertendo.Nome.em.Codigo.de.Linha.xlsx)

@beatriz-paz vi que tu usou as letras em maiúsculo. Se assim for, os códigos de linhas estão todos OK. Porém o número ASCII e sua conversão para binário não batem. O exemplo é a letra "A" (65), que se for "a" é 97 - e no teu exercício o binário é 65 (01000001). Corrija os números ASCII ou refaça os códigos. Como não está especificado na tarefa se é em maiúsculo ou minúsculo, qualquer solução dessas é aceita.

**Comment by beatriz-paz** [comment]
Bom dia @boidacarapreta,

Segue exercício corrigido:

[01 - Exercício - Convertendo Nome em Código de Linha.xlsx](https://github.com/gameif/jogo-web/files/5709384/01.-.Exercicio.-.Convertendo.Nome.em.Codigo.de.Linha.xlsx)

**Comment by ghost** [comment]
> Bom dia @boidacarapreta,
> 
> Segue exercício corrigido:
> 
> [01 - Exercício - Convertendo Nome em Código de Linha.xlsx](https://github.com/gameif/jogo-web/files/5709384/01.-.Exercicio.-.Convertendo.Nome.em.Codigo.de.Linha.xlsx)

@beatriz-paz perfeito! Tarefa entregue.
