### ISSUE TITLE
Definir o jogo 

### ISSUE THREAD

**Issue by beatriz-paz** [gameif/jogo-web#7]
- [ ]  Referências: literatura, mídias em geral e outros jogo
- [ ] Roteiro: primeiros passos da aventura
- [ ] Personagens: perfis, evolução
- [ ] Artefatos: armas, poções etc.
- [ ]  Mundo/universo

**Comment by YasminV12** [comment]
Roteiro: O jogador é convocado para a 3ª Guerra Mundial e o oponente rival sequestra sua família, para conseguir libertar sua família ele precisa escolher entre se entregar para os rivais ou esquematizar um plano para tentar salvar sua família.  
Personagem: próprio jogador    
Tema: 3ª Guerra Mundial 
Local: IFSC-SJ
Objetivo: Vencer as tarefas e conseguir a liberdade da família e própria vida.
