### ISSUE TITLE
Estudar sobre construção de jogos

### ISSUE THREAD

**Issue by beatriz-paz** [gameif/jogo-web#8]
Sobre a construção de personagens:

- [x] [https://ed.ted.com/lessons/what-makes-a-hero-matthew-winkler](url) (vídeo do TED-ed)
- [x] [https://www.editoraaleph.com.br/a-jornada-do-escritor/p](url)  (livro de Christopher Vogler)

Sobre jogos digitais:

- [x] [https://www.youtube.com/user/McBacon1337](url) (canal do Youtube)

**Comment by beatriz-paz** [comment]
Para nos ajudar na construção do nosso jogo, esse site é bem bacana:

https://www.fabricadejogos.net/

Se formos em categorias>>tutorias, e pesquisar por histórias interativas:

![image](https://user-images.githubusercontent.com/75676327/102922954-a2e56a00-446d-11eb-812c-c77d08f6024e.png)

**Comment by beatriz-paz** [comment]
Tutorial sobre o twine:

https://contrafatual.com/2019/11/03/tutorial-de-twine-2-sugarcube/

**Comment by ghost** [comment]
Eu recomendo usar o tema Harlowe ao invés do SugarCube, pois encontrei mais documentação e exemplos, além de ter boas funcionalidades prontas de jogos. 

Aproveitando a data: Feliz Natal!
